### ISSUE TITLE
RSS Support

### ISSUE THREAD

**Issue by BasixKOR** [anaclumos/heimdall#16]
Could we have an RSS feed for HN newsletters? I think it would be easier for folks uses an RSS reader.

**Comment by anaclumos** [comment]
I do have very basic RSS support for English articles. Check this [link](https://raw.githubusercontent.com/anaclumos/hn.cho.sh/main/public/zapier.xml). It's a very rudimentary RSS, so I'd advise using services like [Kill the Newsletter!](https://kill-the-newsletter.com/) to convert it to RSS automatically. #9 

Ultimately, I have plans for a much bigger v2 of this. RSS will be one of the features. It won't come any time soon, but you can track the progress here: [Project Heimdall @ Sunghyun Cho](https://cho.sh/r/9DC5BA)

**Comment by BasixKOR** [comment]
Nice to know there's a readily available RSS feed. Can we keep this issue open so people can subscribe when RSS v2 is implemented?

**Comment by anaclumos** [comment]
Implemented. Let me know if this works.

- English: https://hn.cho.sh/rss/en.xml
- 한국어: https://hn.cho.sh/rss/ko.xml
- Works for all 30 locals

**Comment by ysm-dev** [comment]
@anaclumos 

I think you include wrong RSS content.

Each items of rss should be each newsletter link like this:

```xml
<channel>
  <atom:link href="http://hn.cho.sh/rss/ko.xml" rel="self" type="application/rss+xml"/>
  <title>헤임달</title>
  <link>https://hn.cho.sh/ko</link>
  <description></description>
  <language>ko</language>
  <item>
    <guid isPermaLink="false">https://hn.cho.sh/ko/2023/08/07</guid>
    <title>2023-08-07 | Heimdall</title>
    <link>https://hn.cho.sh/ko/2023/08/07</link>
    // ...
  </item>
  // ...
</channel>
```

And I think you can fill guid with just link

**Comment by anaclumos** [comment]
That's actually intended so that the feed would look like this, which I think feels more natural to skim as stories.

![image](https://github.com/anaclumos/heimdall/assets/31657298/2c20fb36-3aca-4e03-b3b7-3a13bcd372c6)

![image](https://github.com/anaclumos/heimdall/assets/31657298/1ae26232-e62e-43e6-b18a-880989bc1094)

But I understand what you mean. Do you prefer each item to be the whole newsletter? I can also make that as well.

**Comment by ysm-dev** [comment]
@anaclumos 

Yeah, I prefer that, because I follow some others (e.g. GeekNews, https://twitter.com/betterhn300), too.

So I want to treat this as individual "Newsletter", even with the "Same content".

e.g.
hn.cho.sh > https://explore.zoom.us/en/terms      ----> 'Oh, this is "about zoom news"(content) from "hn.cho.sh newsletter"(context)'

GeekNews > https://explore.zoom.us/en/terms.       ----> 'Oh, this is "about zoom news"(content) from "GeekNews"(context)'

betterhn300 > https://explore.zoom.us/en/terms.        ----> 'Oh, this is "about zoom news"(content) from "betterhn twitter account"(context)'

**Comment by anaclumos** [comment]
Gotcha. Will work on it soon.

**Comment by anaclumos** [comment]
@ysm-dev as you wish...

## Story-based RSS feed

- Each item is a single story.
- https://hn.cho.sh/rss/story/en.xml
- https://hn.cho.sh/rss/story/ko.xml

## Newsletter-issue-based RSS feed

- Each item is one issue of a newsletter you would get as an email.
- https://hn.cho.sh/rss/newsletter/en.xml
- https://hn.cho.sh/rss/newsletter/ko.xml

Also, I am looking for company sponsors. @BasixKOR @ysm-dev Can I slide you a DM for this?

**Comment by ysm-dev** [comment]
Yes, but currently I'm not belong to any company

btw this link contains only single latest item: https://hn.cho.sh/rss/newsletter/ko.xml
Maybe better to include recent 10~20 items.

**Comment by anaclumos** [comment]
It now includes the most recent 10 items. 😃

**Comment by ysm-dev** [comment]
All the title and link of each items look wrong data...?

**Comment by anaclumos** [comment]
@BasixKOR Can you check now if it's working as intended?

**Comment by BasixKOR** [comment]
Works like a charm on my Miniflux instance. Thanks for working on this, I appreciate your efforts.
